# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npx truffle compile
    - run: mkdir -p tmp
    - run: node hooks/extract-abi.js tmp
    - run: cmp app/public/RewardCourts.json tmp/RewardCourts.json
    - run: cmp app/public/RewardCourtNames.json tmp/RewardCourtNames.json
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
